version: '2.1'
services:
  client:
    build: client/
    command: bash -c "javac *.java && java OrdersUI"
    tty: true
    stdin_open: true
    depends_on:
     - server
    volumes:
     - ./client:/var/www/java
  server:
    build: server/
    command: bash -c "node Server.js"
    volumes: 
     - ./server:/usr/app
     - /usr/app/node_modules
    ports: 
     - "3000:3000"
    depends_on:
      mysql-container:
        condition: service_healthy
  mysql-container:
    build: ../Database/
    volumes:
     - mysql-storage:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10

volumes:
  mysql-storage:
